<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../VNS.3CStats.Application/VNS.3CStats.Application.csproj" />
    <ProjectReference Include="../VNS.3CStats.Domain/VNS.3CStats.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.20" />
  </ItemGroup>
</Project>
